const VERTICES_PER_PLAYER = 26; // # of vertices in a player body
const PLAYER_BYTES = VERTICES_PER_PLAYER * 8 + 16;

const VERTICES_PER_BULLET = 4;
const BULLET_BYTES = VERTICES_PER_BULLET * 8 + 4;

const INVENTORY_COLLAPSED_HEIGHT = 80;
const INVENTORY_SELECTED_HEIGHT = 90;
const INVENTORY_ANIMATION_SPEED = 80; // px / sec

const PLAYER_COLOR = "#fc7";
const OBJECT_COLOR = "#655";
const PLAYER_OUTLINE = true;
const PLAYER_OUTLINE_COLOR = "#000";
const PLAYER_OUTLINE_WIDTH = 7;
const OBJECT_OUTLINE = true;
const OBJECT_OUTLINE_COLOR = "#000";
const OBJECT_OUTLINE_WIDTH = 2;

const GREATEST_Y_VALUE = 7000;
const LEAST_Y_VALUE = 1000;
