const VERTICES_PER_BULLET = 4;

const INVENTORY_COLLAPSED_HEIGHT = 80;
const INVENTORY_SELECTED_HEIGHT = 90;
const INVENTORY_ANIMATION_SPEED = 80; // px / sec

const STATS_WIDTH = 200;
const STATS_HEIGHT = 280;

const SHOP_MENU_MARGIN = 10;
const SHOP_MENU_PADDING = 5;
const SHOP_MENU_TEXT_HEIGHT = 18;

const PLAYER_COLOR = "#fc7";
const PLAYER_OUTLINE = true;
const PLAYER_OUTLINE_COLOR = "#000";
const PLAYER_OUTLINE_WIDTH = 3;
const MOUNTAIN_TEXURE_WIDTH = 200;
const MOUNTAIN_TEXURE_HEIGHT = 200;
const OBJECT_OUTLINE = true;
const OBJECT_OUTLINE_COLOR = "#000";
const OBJECT_OUTLINE_WIDTH = 2;
const FRAME_WIDTH = 2000;

// For the background gradient
const GREATEST_Y_VALUE = 8000;
const LEAST_Y_VALUE = 0;
